In [1]:
import os
import pickle
import numpy as np
import random
np.set_printoptions(suppress=True)

In [2]:
batch_size=48
seq_length=1
datasets=[0, 1, 2, 3, 4]
forcePreProcess=False
infer=False
data_dirs = ['./data/eth/univ', './data/eth/hotel',
                  './data/ucy/zara/zara01', './data/ucy/zara/zara02',
                  './data/ucy/univ']
used_data_dirs = [data_dirs[x] for x in datasets]
infer = infer

# Number of datasets
numDatasets = len(data_dirs)

# Data directory where the pre-processed pickle file resides
data_dir = './data'

# Store the arguments
batch_size = batch_size
seq_length = seq_length

# Validation arguments
val_fraction = 0.2

In [3]:
data_file = os.path.join(data_dir, "trajectories_1.pkl")

In [4]:
data_dirs=used_data_dirs

In [5]:
all_frame_data = []
valid_frame_data = []
frameList_data = []
numPeds_data = []
dataset_index = 0

In [6]:
for directory in data_dirs:
    file_path = os.path.join(directory, 'pixel_pos_interpolate_1.csv')
    data = np.genfromtxt(file_path, delimiter=',')
    frameList = np.unique(data[0, :]).tolist()
    numFrames = len(frameList)
    frameList_data.append(frameList)
    numPeds_data.append([])
    all_frame_data.append([])
    valid_frame_data.append([])
    skip = 10
    for ind, frame in enumerate(frameList):
        if ind % skip != 0:
            continue
        pedsInFrame=data[:, data[0, :] == frame]
        pedsList = pedsInFrame[1, :].tolist()
        numPeds_data[dataset_index].append(pedsList)
        pedsWithPos = []
        for ped in pedsList:
            current_x = pedsInFrame[3, pedsInFrame[1, :] == ped][0]
            current_y = pedsInFrame[2, pedsInFrame[1, :] == ped][0]
            pedsWithPos.append([ped, current_x, current_y])
        if (ind > numFrames * val_fraction) or (infer):
            all_frame_data[dataset_index].append(np.array(pedsWithPos))
        else:
            valid_frame_data[dataset_index].append(np.array(pedsWithPos))
    dataset_index += 1
f = open(data_file, "wb")
pickle.dump((all_frame_data, frameList_data, numPeds_data, valid_frame_data), f, protocol=2)
f.close()

In [7]:
all_frame_data[0]

[array([[1301.        ,    0.26749883,    0.96355819],
        [1302.        ,    0.26653514,    0.9638252 ],
        [1303.        ,    0.26557118,    0.96409126],
        [1304.        ,    0.26460695,    0.96435635],
        [1305.        ,    0.26364247,    0.96462047],
        [1306.        ,    0.26267771,    0.96488363],
        [1307.        ,    0.2617127 ,    0.96514583],
        [1308.        ,    0.26074742,    0.96540706],
        [1309.        ,    0.25978188,    0.96566732],
        [1310.        ,    0.25881609,    0.96592662]]),
 array([[1401.        ,    0.16996714,    0.98544973],
        [1402.        ,    0.16898161,    0.9856192 ],
        [1403.        ,    0.16799591,    0.98578769],
        [1404.        ,    0.16701003,    0.9859552 ],
        [1405.        ,    0.166024  ,    0.98612171],
        [1406.        ,    0.16503779,    0.98628724],
        [1407.        ,    0.16405142,    0.98645179],
        [1408.        ,    0.16306489,    0.98661535],
        

In [8]:
frameList_data

[[1.0,
  2.0,
  3.0,
  4.0,
  5.0,
  6.0,
  7.0,
  8.0,
  9.0,
  10.0,
  11.0,
  12.0,
  13.0,
  14.0,
  15.0,
  16.0,
  17.0,
  18.0,
  19.0,
  20.0,
  21.0,
  22.0,
  23.0,
  24.0,
  25.0,
  26.0,
  27.0,
  28.0,
  29.0,
  30.0,
  31.0,
  32.0,
  33.0,
  34.0,
  35.0,
  36.0,
  37.0,
  38.0,
  39.0,
  40.0,
  41.0,
  42.0,
  43.0,
  44.0,
  45.0,
  46.0,
  47.0,
  48.0,
  49.0,
  50.0,
  51.0,
  52.0,
  53.0,
  54.0,
  55.0,
  56.0,
  57.0,
  58.0,
  59.0,
  60.0,
  61.0,
  62.0,
  63.0,
  64.0,
  65.0,
  66.0,
  67.0,
  68.0,
  69.0,
  70.0,
  71.0,
  72.0,
  73.0,
  74.0,
  75.0,
  76.0,
  77.0,
  78.0,
  79.0,
  80.0,
  81.0,
  82.0,
  83.0,
  84.0,
  85.0,
  86.0,
  87.0,
  88.0,
  89.0,
  90.0,
  91.0,
  92.0,
  93.0,
  94.0,
  95.0,
  96.0,
  97.0,
  98.0,
  99.0,
  100.0,
  101.0,
  102.0,
  103.0,
  104.0,
  105.0,
  106.0,
  107.0,
  108.0,
  109.0,
  110.0,
  111.0,
  112.0,
  113.0,
  114.0,
  115.0,
  116.0,
  117.0,
  118.0,
  119.0,
  120.0,
  121.0,
  122.0,
  123.0,
 

In [9]:
numPeds_data[1]

[[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
 [101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0],
 [201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0],
 [301.0, 302.0, 303.0, 304.0, 305.0, 306.0, 307.0, 308.0, 309.0, 310.0],
 [401.0, 402.0, 403.0, 404.0, 405.0, 406.0, 407.0, 408.0, 409.0, 410.0],
 [501.0, 502.0, 503.0, 504.0, 505.0, 506.0, 507.0, 508.0, 509.0, 510.0],
 [601.0, 602.0, 603.0, 604.0, 605.0, 606.0, 607.0, 608.0, 609.0, 610.0],
 [701.0, 702.0, 703.0, 704.0, 705.0, 706.0, 707.0, 708.0, 709.0, 710.0],
 [801.0, 802.0, 803.0, 804.0, 805.0, 806.0, 807.0, 808.0, 809.0, 810.0],
 [901.0, 902.0, 903.0, 904.0, 905.0, 906.0, 907.0, 908.0, 909.0, 910.0],
 [1001.0,
  1002.0,
  1003.0,
  1004.0,
  1005.0,
  1006.0,
  1007.0,
  1008.0,
  1009.0,
  1010.0],
 [1101.0,
  1102.0,
  1103.0,
  1104.0,
  1105.0,
  1106.0,
  1107.0,
  1108.0,
  1109.0,
  1110.0],
 [1201.0,
  1202.0,
  1203.0,
  1204.0,
  1205.0,
  1206.0,
  1207.0,
  1208.0,
  1209.

In [10]:
valid_frame_data

[[array([[ 1.        ,  1.        ,  0.        ],
         [ 2.        ,  0.9999995 ,  0.001     ],
         [ 3.        ,  0.999998  ,  0.002     ],
         [ 4.        ,  0.9999955 ,  0.003     ],
         [ 5.        ,  0.999992  ,  0.00399999],
         [ 6.        ,  0.9999875 ,  0.00499998],
         [ 7.        ,  0.999982  ,  0.00599996],
         [ 8.        ,  0.9999755 ,  0.00699994],
         [ 9.        ,  0.999968  ,  0.00799991],
         [10.        ,  0.9999595 ,  0.00899988]]),
  array([[101.        ,   0.99500416,   0.09983342],
         [102.        ,   0.99490383,   0.10082837],
         [103.        ,   0.99480251,   0.10182322],
         [104.        ,   0.99470019,   0.10281798],
         [105.        ,   0.99459687,   0.10381262],
         [106.        ,   0.99449256,   0.10480717],
         [107.        ,   0.99438726,   0.10580161],
         [108.        ,   0.99428096,   0.10679594],
         [109.        ,   0.99417367,   0.10779017],
         [110.       

In [11]:
frame

629.0

In [12]:

pedsList

[6201.0,
 6202.0,
 6203.0,
 6204.0,
 6205.0,
 6206.0,
 6207.0,
 6208.0,
 6209.0,
 6210.0]

In [13]:
len(pedsList)

10

In [14]:
numPeds_data

[[[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
  [101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0],
  [201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0],
  [301.0, 302.0, 303.0, 304.0, 305.0, 306.0, 307.0, 308.0, 309.0, 310.0],
  [401.0, 402.0, 403.0, 404.0, 405.0, 406.0, 407.0, 408.0, 409.0, 410.0],
  [501.0, 502.0, 503.0, 504.0, 505.0, 506.0, 507.0, 508.0, 509.0, 510.0],
  [601.0, 602.0, 603.0, 604.0, 605.0, 606.0, 607.0, 608.0, 609.0, 610.0],
  [701.0, 702.0, 703.0, 704.0, 705.0, 706.0, 707.0, 708.0, 709.0, 710.0],
  [801.0, 802.0, 803.0, 804.0, 805.0, 806.0, 807.0, 808.0, 809.0, 810.0],
  [901.0, 902.0, 903.0, 904.0, 905.0, 906.0, 907.0, 908.0, 909.0, 910.0],
  [1001.0,
   1002.0,
   1003.0,
   1004.0,
   1005.0,
   1006.0,
   1007.0,
   1008.0,
   1009.0,
   1010.0],
  [1101.0,
   1102.0,
   1103.0,
   1104.0,
   1105.0,
   1106.0,
   1107.0,
   1108.0,
   1109.0,
   1110.0],
  [1201.0,
   1202.0,
   1203.0,
   1204.0,
   1205.0,
  

In [15]:
np.array(numPeds_data).shape

(5, 63, 10)

In [16]:
pedsList

[6201.0,
 6202.0,
 6203.0,
 6204.0,
 6205.0,
 6206.0,
 6207.0,
 6208.0,
 6209.0,
 6210.0]

In [17]:
ped

6210.0

In [19]:
np.array(valid_frame_data).shape

(5, 13, 10, 3)

In [20]:
np.array(all_frame_data).shape

(5, 50, 10, 3)

In [23]:
valid_frame_data

[[array([[ 1.        ,  1.        ,  0.        ],
         [ 2.        ,  0.9999995 ,  0.001     ],
         [ 3.        ,  0.999998  ,  0.002     ],
         [ 4.        ,  0.9999955 ,  0.003     ],
         [ 5.        ,  0.999992  ,  0.00399999],
         [ 6.        ,  0.9999875 ,  0.00499998],
         [ 7.        ,  0.999982  ,  0.00599996],
         [ 8.        ,  0.9999755 ,  0.00699994],
         [ 9.        ,  0.999968  ,  0.00799991],
         [10.        ,  0.9999595 ,  0.00899988]]),
  array([[101.        ,   0.99500416,   0.09983342],
         [102.        ,   0.99490383,   0.10082837],
         [103.        ,   0.99480251,   0.10182322],
         [104.        ,   0.99470019,   0.10281798],
         [105.        ,   0.99459687,   0.10381262],
         [106.        ,   0.99449256,   0.10480717],
         [107.        ,   0.99438726,   0.10580161],
         [108.        ,   0.99428096,   0.10679594],
         [109.        ,   0.99417367,   0.10779017],
         [110.       

In [27]:
all_frame_data

[[array([[1301.        ,    0.26749883,    0.96355819],
         [1302.        ,    0.26653514,    0.9638252 ],
         [1303.        ,    0.26557118,    0.96409126],
         [1304.        ,    0.26460695,    0.96435635],
         [1305.        ,    0.26364247,    0.96462047],
         [1306.        ,    0.26267771,    0.96488363],
         [1307.        ,    0.2617127 ,    0.96514583],
         [1308.        ,    0.26074742,    0.96540706],
         [1309.        ,    0.25978188,    0.96566732],
         [1310.        ,    0.25881609,    0.96592662]]),
  array([[1401.        ,    0.16996714,    0.98544973],
         [1402.        ,    0.16898161,    0.9856192 ],
         [1403.        ,    0.16799591,    0.98578769],
         [1404.        ,    0.16701003,    0.9859552 ],
         [1405.        ,    0.166024  ,    0.98612171],
         [1406.        ,    0.16503779,    0.98628724],
         [1407.        ,    0.16405142,    0.98645179],
         [1408.        ,    0.16306489,    0.9

In [28]:
np.array(all_frame_data).shape

(5, 50, 10, 3)